### ISSUE TITLE
Modified code to support Android Studio specific changes

### ISSUE THREAD

**Issue by emkishan** [aditya619/NextTransit#10]
Updated the app to support Gradle builds. It is much cleaner and easier to integrate APIs (especially google services). However, I am still getting an error while trying to fetch the map. The exact error is "E/Google Maps Android API﹕ Failed to load map. Error contacting Google servers. This is probably an authentication issue (but could be due to network errors)."
- I have confirmed that the error is not a network error and I am trying to fix the error.

**Comment by ghost** [comment]
If it is an authentication issue, could it be because we need some kind of key to access the gmaps andriod api ?

**Comment by emkishan** [comment]
it looked to be an authentication issue. I pushed with a new key and now it started working.
You can checkout gradle-change branch and run and let me know if you see any issues.
